name: Mainline Build And Release

on:
  push:
    branches:
      - "mainline"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Elevate wrapper permissions
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Rename built mod
      run: mv build/libs/xaeroplus-*.jar xaeroplus-${{ github.run_number }}.jar

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: xaeroplus-${{ github.run_number }}
        path: xaeroplus-${{ github.run_number }}.jar

    - name: Download Xaero WorldMap
      run: wget https://chocolateminecraft.com/mods2/worldmap/XaerosWorldMap_1.30.3_Forge_1.12.jar --no-check-certificate

    - name: Download Xaero Minimap
      run: wget https://chocolateminecraft.com/mods2/minimap/Xaeros_Minimap_23.4.4_Forge_1.12.jar --no-check-certificate

    - name: Create modpack zip
      run: tar -czvf xaeroplus-modpack-${{ github.run_number }}.zip xaeroplus-${{ github.run_number }}.jar XaerosWorldMap_1.30.3_Forge_1.12.jar Xaeros_Minimap_23.4.4_Forge_1.12.jar

    - name: Release Artifact
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        automatic_release_tag: "latest"
        title: "Latest Release - ${{ github.run_number }}"
        files: |
          xaeroplus-*.jar
          xaeroplus-modpack-*.zip
