name: Mainline Build And Release

on:
  push:
    branches:
      - "mainline"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'

    - name: Elevate wrapper permissions
      run: chmod +x ./gradlew

    - name: Build mod
      run: ./gradlew build

    - name: Rename built mod
      run: mv build/libs/xaeroplus-*.jar xaeroplus-${{ github.run_number }}.jar

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: xaeroplus-${{ github.run_number }}
        path: xaeroplus-${{ github.run_number }}.jar

    - name: Release Artifact
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          xaeroplus-*.jar
